server:
  port: 52749
  base-url: /pizarra
db:
  motor: postgresql
  host: localhost
  database: pizarra_db
  port: 54313
  schema: piz
  user: pizarra_user
login:
  table: users
  userFieldName: username
  passFieldName: md5pass
  infoFieldList: [username, rol]
  rolFieldName: rol
  plus:
    unloggedPath: client/unlogged
    loginPagePath: client/unlogged
    successRedirect: /